# Server 1: Nginx Rate Limitting Configuration
# Path on Server: /etc/nginx/nginx.conf

# Place inside the http{} block:
limit_req_zone $binary_remote_addr zone=mylimit:10m rate=5r/m;  # Limits each unique IP to 5 requests per minute.

# Place inside the relevent server{} block:
limit_req zone=mylimit burst=5 nodelay;   # Allows a short burst of upto 5 requests before strictly enforcing the rate limit.